name: AzDo

on:
  release:
    types: [published,workflow_dispatch]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: 'https://dev.azure.com/sk4red/PipeLineTest'
            azure-pipeline-name: 'Dev Release PipeLine'
            azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'